// <auto-generated />
namespace SistemaGerenciamento.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alteracaonovamentenoprepedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaonovamentenoprepedido));
        
        string IMigrationMetadata.Id
        {
            get { return "202410310231378_alteracao novamente no prepedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
