// <auto-generated />
namespace SistemaGerenciamento.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class atualizandonomedocampoindeleteview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizandonomedocampoindeleteview));
        
        string IMigrationMetadata.Id
        {
            get { return "202410310247323_atualizando nome do campo in delete view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
